### ISSUE TITLE
error select options

### ISSUE THREAD

**Issue by andrescastro7036** [IncredibleHacker/TBomb2.0#4]
![image](https://user-images.githubusercontent.com/83835568/121729894-97860980-cab4-11eb-8bb6-e04ec9c86682.png)

**Comment by IncredibleHacker** [comment]
Please re clone (uninstall and reinstall the script) then this issue will not come as i have updated the script.
Uninstall command :- rm -rf TBomb
Reinstall command :- git clone https://github.com/IncredibleHacker/TBomb2.0

**Comment by IncredibleHacker** [comment]
Please re clone (uninstall and reinstall the script) then this issue will not come as i have updated the script.
Uninstall command :- rm -rf TBomb
Reinstall command :- git clone https://github.com/IncredibleHacker/TBomb2.0
